languageCode = "en"
languageName = "English"
weight = 1
title = "home"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Life is fast, code to fun."

[params.author]
  name = "Do Huy Hoang"
  email = "dohuyhoangvn93@gmail.com"
  image = "img/profile.png"
  headline = "Life is fast. Code to fun."
  bio = "Dev - Rust - Python - AI research."
  links = [
    { facebook = "https://fb.com/huyhoangnd/" },
    { github = "https://github.com/dohuyhoangvn93/" },
  ]